import jsPDF from 'jspdf';

interface COAEntry {
  sampleName: string;
  testDate: string;
  measuredAmount: string;
  purity?: string;
  taskNumber: string;
  verifyKey: string;
}

interface PeptideForPdf {
  shortName: string;
  name: string;
  category: string;
  janoshikPurity?: number;
  janoshikDate?: string;
  janoshikCOA: COAEntry[];
}

export function generateCOAPdf(peptide: PeptideForPdf) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Certificate of Analysis Report', pageWidth / 2, y, { align: 'center' });
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text('Independent Third-Party Testing by Janoshik Analytical', pageWidth / 2, y, { align: 'center' });
  y += 12;

  // Divider
  doc.setDrawColor(200);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // Peptide info
  doc.setTextColor(0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(peptide.shortName, 20, y);
  y += 6;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80);
  doc.text(peptide.name, 20, y);
  y += 6;

  doc.text(`Category: ${peptide.category}`, 20, y);
  if (peptide.janoshikPurity) {
    doc.text(`Overall Purity: ${peptide.janoshikPurity}%`, pageWidth / 2, y);
  }
  y += 6;

  doc.text(`Total Certificates: ${peptide.janoshikCOA.length}`, 20, y);
  doc.text(`Report Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, y);
  y += 12;

  // COA entries
  peptide.janoshikCOA.forEach((coa, index) => {
    // Check if we need a new page
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    // Card background
    doc.setFillColor(245, 247, 250);
    doc.roundedRect(20, y - 4, pageWidth - 40, 44, 3, 3, 'F');

    doc.setTextColor(0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}. ${coa.sampleName}`, 25, y + 4);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(`Test Date: ${coa.testDate}`, pageWidth - 25, y + 4, { align: 'right' });

    y += 12;
    doc.setTextColor(60);
    doc.text(`Measured Amount: ${coa.measuredAmount}`, 25, y);
    if (coa.purity) {
      doc.text(`Purity: ${coa.purity}`, 110, y);
    }

    y += 6;
    doc.text(`Task Number: ${coa.taskNumber}`, 25, y);
    doc.text('Manufacturer: ZZTai-Tech', 110, y);

    y += 6;
    if (coa.verifyKey) {
      doc.setTextColor(40, 100, 200);
      doc.text(`Verification Key: ${coa.verifyKey}`, 25, y);
      doc.setTextColor(100);
      doc.text('Verify at: janoshik.com/verify', 110, y);
    }

    y += 14;
  });

  // Footer
  if (y > 260) {
    doc.addPage();
    y = 20;
  }
  y += 5;
  doc.setDrawColor(200);
  doc.line(20, y, pageWidth - 20, y);
  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(140);
  doc.text('This report is for informational purposes only. Verify all certificates at janoshik.com/verify', pageWidth / 2, y, { align: 'center' });
  y += 4;
  doc.text('Generated by Peptide Research Tracker', pageWidth / 2, y, { align: 'center' });

  doc.save(`COA-Report-${peptide.shortName.replace(/\s+/g, '-')}.pdf`);
}
