// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  OWNED_SUPABASE_PUBLISHABLE_KEY,
  OWNED_SUPABASE_URL,
} from './public-config';

const CONFIGURED_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const CONFIGURED_SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// The tracker is intentionally pinned to the company-owned project. A matching
// hosted key can be rotated through deployment variables; stale variables from
// the retired deployment are ignored rather than redirecting user data.
const normalizedConfiguredUrl = CONFIGURED_SUPABASE_URL?.trim().replace(/\/$/, '');
const hasOwnedDeploymentConfig =
  normalizedConfiguredUrl === OWNED_SUPABASE_URL &&
  Boolean(CONFIGURED_SUPABASE_KEY?.trim());
const SUPABASE_URL = OWNED_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = hasOwnedDeploymentConfig
  ? CONFIGURED_SUPABASE_KEY!.trim()
  : OWNED_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = true;

const PLACEHOLDER_PATTERNS = [
  /^your-?supabase-?url$/i,
  /^your-?anon-?key$/i,
  /^your-?publishable-?key$/i,
  /^https:\/\/your-?project-?id\.supabase\.co$/i,
  /^https:\/\/example\.supabase\.co$/i,
  /^https:\/\/localhost(:\d+)?$/i,
  /^placeholder$/i,
  /^xxx+$/i,
  /\bTODO\b/i,
];

function isPlaceholder(value: string): boolean {
  return PLACEHOLDER_PATTERNS.some(p => p.test(value));
}

function warnIfStaleDeploymentConfig(): void {
  if (typeof window === 'undefined' || !import.meta.env.DEV) return;

  if (
    CONFIGURED_SUPABASE_URL &&
    (normalizedConfiguredUrl !== OWNED_SUPABASE_URL ||
      !CONFIGURED_SUPABASE_KEY ||
      isPlaceholder(CONFIGURED_SUPABASE_KEY))
  ) {
    console.warn('[Supabase Config] Ignoring stale hosted configuration; using the owned tracker project.');
  }
}

warnIfStaleDeploymentConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// During build-time prerender there is no browser localStorage. Fall back to a
// no-op in-memory store so module import doesn't crash; in the browser (and in
// the native Capacitor build) the real localStorage is used exactly as before.
const isBrowser = typeof window !== 'undefined' && typeof window.localStorage !== 'undefined';
const memoryStore: Record<string, string> = {};
const authStorage = isBrowser
  ? window.localStorage
  : {
      getItem: (k: string) => (k in memoryStore ? memoryStore[k] : null),
      setItem: (k: string, v: string) => { memoryStore[k] = v; },
      removeItem: (k: string) => { delete memoryStore[k]; },
    };

export const supabase = createClient<Database, 'tracker'>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'tracker',
  },
  auth: {
    storage: authStorage,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});
